### ISSUE TITLE
Confusing error message when offline

### ISSUE THREAD

**Issue by nicklauslittle-gov** [airpwr/airpwr#91]
There is a confusing error message when trying to pull without an online network connection:

```pwsh
PS C:\Users\User\Project> pwr version

Major  Minor  Build  Revision
-----  -----  -----  --------
0      6      0      24

PS C:\Users\User\Project> pwr pull
pwr : Exception calling "GetResult" with "0" argument(s): "An error occurred while sending the request."
At line:1 char:1
+ pwr pull
+ ~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Airpower
```

**Comment by troyaf** [comment]
What would you like the error message to be? I'll update it.

**Comment by nicklauslittle** [comment]
How about, "Jesus saves, so if you get online and tell everyone about it, we'll pull those packages for you!"?

**Comment by nicklauslittle** [comment]
Just kidding. I think what immediately drew my attention was the `Exception calling "GetResult" with "0" argument(s)`, so if there's a way to put the error message before that then I think that would help. Is that possible?

For the error message, something about `Can't pull package, because the request could not contact the server` or maybe even put an additional comment in there: `An error occurred while sending the request; is there an active Internet connection?` I don't have any great ideas, but I just stared at the error message for like a minute before I could figure out what was going on. (Of course, I assumed my Internet connection was working until I noticed the little globe in the corner.)
